### ISSUE TITLE
Host this as `devguide.julialang.org`?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/devguide.julialang.org#1]
I can't take credit for the idea; it was brought up by @tecosaur and @ViralBShah on Slack.

It could be cool to host this guide at `devguide.julialang.org` or something like that. We can definitely bikeshed the name. Once we've decided on the name, Viral and I can help with setting up the DNS CNAME to point to GitHub Pages.

**Comment by StefanKarpinski** [comment]
Maybe rename the repo to `devdocs` in that case? Or just `devguide`? We could also rename the devdocs in the manual to "Internals" since we're going to split out advice for developing Julia from details about the internals of a specific Julia version.

**Comment by DilumAluthge** [comment]
Yeah, once we've decided on the domain name we want, we should rename this repo to match that domain name, to make things easier.

**Comment by DilumAluthge** [comment]
@StefanKarpinski @ViralBShah @tecosaur Does anyone have a strong preference between `devguide.julialang.org` and `devdocs.julialang.org`? Or does anyone have an alternate suggestion?

**Comment by tecosaur** [comment]
I slightly prefer the first, I think it does a better job of delineating itself from documentation on the internals/build instructions, etc. and signalling that it should help guide development of Julia itself. No strong preference though.

Just for reference, Python and Rust's equivalents seem to be "dev guide" themed names:
- https://devguide.python.org/
- https://rustc-dev-guide.rust-lang.org/

**Comment by StefanKarpinski** [comment]
Agree that devguide seems to be clearer and more standard. Let's go with that. So we're splitting devdocs into "devguide" outside of the manual for guidance on how to develop Julia and "Internals" in the manual for documentation about the internals of a specific version of Julia.

**Comment by DilumAluthge** [comment]
Cool, I've renamed the repo, and I've set the custom domain in this repo's admin settings.

I'll do the Namecheap steps (add a CNAME pointing the `devguide` subdomain to GitHub Pages) when I'm back at my computer, unless someone beats me to it.

**Comment by tecosaur** [comment]
(re: Stefan) That's both my understanding and what I had in mind :slightly_smiling_face:

**Comment by DilumAluthge** [comment]
I've created a new CNAME record that points from `devguide.julialang.org.` to `julialang.github.io.`, with TTL set to "automatic".

It may take a little while for the record to propagate.

**Comment by DilumAluthge** [comment]
The guide should now be accessible over HTTP at: http://devguide.julialang.org/

I've enabled HTTPS in the repo's GitHub Pages settings, but it may take up to 24 hours for GitHub to provision the SSL certificate and set up HTTPS. (AFAICT, no further action is needed from us for HTTPS; GitHub should complete all the remaining steps by themselves.)

**Comment by ViralBShah** [comment]
We should hold off on advertising this until much of the guide has content (lots of sections are empty right now). 

Will the Julia internals also move here?

**Comment by StefanKarpinski** [comment]
No, Internals is tied to a specific Julia version so should live in the manual.

**Comment by DilumAluthge** [comment]
The guide should now be available via HTTPS at: https://devguide.julialang.org/

**Comment by DilumAluthge** [comment]
It looks like HTTPS is not yet being enforced. That is, http://devguide.julialang.org/ is not currently automatically redirected to https://devguide.julialang.org/

I've now enabled the "enforce HTTPS" option; let's see how long it takes for that option to kick in.

**Comment by DilumAluthge** [comment]
> We should hold off on advertising this until much of the guide has content (lots of sections are empty right now).

I agree. I've opened an issue to track the progress of filling out each of the currently empty sections: #2

**Comment by DilumAluthge** [comment]
Okay, it looks like http://devguide.julialang.org/ now automatically redirects to https://devguide.julialang.org/

I think that all of the tasks for this issue have been completed, so I'll close this issue as completed.
